import os
import requests
import json
import logging
import time
import re
from typing import List, Dict, Any, Optional, Tuple
from dataclasses import dataclass

from rag_builder.rag.retriever import SubGraphResult

logger = logging.getLogger(__name__)

@dataclass
class GeneratedResponse:
    """
    Represents the final response generated by the RAG system.
    """
    answer: str
    citations: List[Tuple[str, str, str]]  # List of (subject, predicate, object)
    context_used: str
    confidence_score: float = 1.0

class ResponseGenerator:
    """
    Generates grounded responses using an LLM and the retrieved graph context.
    Ensures that responses include citations to the source triplets.
    """

    def __init__(
        self, 
        ollama_url: Optional[str] = None, 
        model: Optional[str] = None
    ):
        """
        Initialize the ResponseGenerator.

        Args:
            ollama_url: URL of the Ollama server. Fallback to OLLAMA_URL env var or default.
            model: The model to use for generation. Fallback to OLLAMA_MODEL env var or default.
        """
        self.ollama_url = ollama_url or os.getenv("OLLAMA_URL", "http://localhost:11434")
        if not self.ollama_url.endswith("/api/generate"):
            base_url = self.ollama_url.rstrip("/")
            self.ollama_url = f"{base_url}/api/generate"
        
        self.model = model or os.getenv("OLLAMA_MODEL", "gemma2")

    def generate(
        self, 
        question: str, 
        context_results: List[SubGraphResult]
    ) -> GeneratedResponse:
        """
        Generates a response grounded in the provided graph context.

        Args:
            question: The user's question.
            context_results: A list of SubGraphResults containing retrieved context.

        Returns:
            A GeneratedResponse containing the grounded answer and citations.
        """
        # Flatten triplets and remove duplicates
        all_triplets = []
        for res in context_results:
            all_triplets.extend(res.triplets)
        
        seen = set()
        unique_triplets = []
        for t in all_triplets:
            if t not in seen:
                unique_triplets.append(t)
                seen.add(t)

        # Build indexed context string: [T0] Subject --(Predicate)--> Object
        indexed_context_lines = []
        for i, t in enumerate(unique_triplets):
            indexed_context_lines.append(f"[T{i}] {t[0]} --({t[1]})--> {t[2]}")
        
        combined_context = "\n".join(indexed_context_lines)
        prompt = self._build_prompt(question, combined_context)

        try:
            response = requests.post(
                self.ollama_url,
                json={
                    "model": self.model,
                    "prompt": prompt,
                    "stream": False,
                    "format": "json"
                },
                timeout=60
            )
            response.raise_for_status()
            result = response.json()
            content = result.get("response", "")
            
            data = json.loads(content)
            answer = data.get("answer", "I could not find an answer in the provided context.")
            cited_ids = data.get("citations", []) # Expected to be ['[T0]', '[T1]']
            
            # Map [Tx] back to the actual Triplet objects
            citations = []
            for cid in cited_ids:
                match = re.search(r"\[T(\d+)\]", cid)
                if match:
                    idx = int(match.group(1))
                    if 0 <= idx < len(unique_triplets):
                        citations.append(unique_triplets[idx])

            return GeneratedResponse(
                answer=answer,
                citations=citations,
                context_used=combined_context
            )

        except (requests.RequestException, json.JSONDecodeError, KeyError) as e:
            logger.error(f"Error generating response: {str(e)}")
            return GeneratedResponse(
                answer=f"An error occurred while generating the response: {str(e)}",
                citations=[],
                context_used=combined_context
            )

    def _build_prompt(self, question: str, context: str) -> str:
        """Constructs the prompt for grounded generation with index-based citations."""
        return (
            f"You are a helpful assistant that answers questions based ONLY on the provided Knowledge Graph context.\n\n"
            f"Context:\n{context}\n\n"
            f"Question: {question}\n\n"
            f"Instructions:\n"
            f"1. If the answer is not present in the context, state that you don't know.\n"
            f"2. Be concise and factual.\n"
            f"3. Use the provided index IDs (e.g., [T0], [T1]) to cite the specific triplets used to form the answer.\n\n"
            f"Respond ONLY in JSON format with the following keys:\n"
            f"- 'answer': The grounded response string.\n"
            f"- 'citations': A list of strings containing the index IDs used (e.g., ['[T0]', '[T2]']).\n"
            f"Example: {{\"answer\": \"Alice works for Acme Corp.\", \"citations\": [\"[T0]\"]}}"
        )
